live_config_reload = true

[font]
size = 12

[font.bold]
family = "JetBrainsMonoNerdFont"
[font.bold_italic]
family = "JetBrainsMonoNerdFont"
[font.italic]
family = "JetBrainsMonoNerdFont"
[font.normal]
family = "JetBrainsMonoNerdFont"

[mouse]
hide_when_typing = true

[scrolling]
history = 1000

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
padding = { x = 12, y = 12 }
