#!/bin/bash
 
# Launch cookie_daemon.py in daemon mode if the default cookie socket doesn't exist
[[ -S $XDG_CACHE_HOME/uzbl/cookie_daemon_socket ]] || $XDG_DATA_HOME/uzbl/scripts/cookie_daemon.py --daemon-mode
 
# Launch uzbl directly
/usr/bin/uzbl $@
