#!/bin/bash
 
# Launch cookie_daemon.py in daemon mode if the default cookie socket doesn't exist
#[[ -S $XDG_CACHE_HOME/uzbl/cookie_daemon_socket ]] || /usr/share/uzbl/examples/data/uzbl/scripts/cookie_daemon.py -v
/usr/share/uzbl/examples/data/uzbl/scripts/cookie_daemon.py -v

# Launch uzbl directly
/usr/bin/uzbl $@
