#!/usr/bin/env python
# Whitespace stripper
# Mason Larobina <mason.larobina@gmail.com>

import sys
def strip(raw):
    raw = '\n'.join([s.rstrip() for s in raw.strip().split("\n")])
    while "\n\n\n\n" in raw:
        raw = raw.replace("\n\n\n\n", "\n\n\n")
    return raw

if __name__ == "__main__":
    if not len(sys.argv[1:]):
        print "usage: %s [FILES..]" % sys.argv[0]
        sys.exit(1)

    for filename in sys.argv[1:]:
        h = open(filename, 'r')
        s = h.read()
        h.close()
        h = open(filename, 'w')
        h.write("%s\n" % strip(s))
        h.close()
