#!/usr/bin/env python2
# Whitespace stripper
# Mason Larobina <mason.larobina@gmail.com>

import sys
import os

def strip(s):
    s = '\n'.join((line.rstrip() for line in s.strip().split('\n')))
    return '\n\n\n'.join(s.split('\n\n\n\n'))

if __name__ == "__main__":
    if not len(sys.argv[1:]):
        print 'usage: %s [FILES..]' % sys.argv[0]
        sys.exit(1)

    for filename in sys.argv[1:]:
        if os.path.isdir(filename): continue
        # Read file
        h = open(filename, 'r')
        s = h.read()
        h.close()
        # Strip whitespace
        text = strip(s)
        # Write file
        h = open(filename, 'w')
        h.write('%s\n' % text)
        h.close()
